class Role:
    STAFF = "STAFF"
    CUSTOMER = "CUSTOMER"

class Permission:
    VIEW_OWN_PROFILE = "VIEW_OWN_PROFILE"
    VIEW_ALL_CUSTOMERS = "VIEW_ALL_CUSTOMERS"
    MANAGE_CUSTOMERS = "MANAGE_CUSTOMERS"
    CREATE_ACCOUNTS = "CREATE_ACCOUNTS"
    VIEW_ALL_ACCOUNTS = "VIEW_ALL_ACCOUNTS"
    MANAGE_ACCOUNT_STATUS = "MANAGE_ACCOUNT_STATUS"
    STAFF_FINANCIAL_OPERATIONS = "STAFF_FINANCIAL_OPERATIONS"
    VIEW_ALL_TRANSACTIONS = "VIEW_ALL_TRANSACTIONS"
    MANAGE_USERS = "MANAGE_USERS"
    VIEW_SYSTEM_STATISTICS = "VIEW_SYSTEM_STATISTICS"
    CUSTOMER_SELF_SERVICE = "CUSTOMER_SELF_SERVICE"
    VIEW_OWN_DATA = "VIEW_OWN_DATA"

class AccountType:
    SAVINGS = "SAVINGS"
    CURRENT = "CURRENT"
    BUSINESS = "BUSINESS"

class DashboardType:
    SYSTEM = "SYSTEM"
    PERSONAL = "PERSONAL"

class TransactionType:
    DEPOSIT = "DEPOSIT"
    WITHDRAWAL = "WITHDRAWAL"
    TRANSFER = "TRANSFER"

class AccountStatus:
    ACTIVE = "ACTIVE"
    FROZEN = "FROZEN"
    CLOSED = "CLOSED"

